### ISSUE TITLE
Using curl for lastest version

### ISSUE THREAD

**Issue by pietro** [cyberark/summon-aws-secrets#16]
The install script uses either curl or wget to downloads the tarball, but only curl to check the latest version, which breakes the install script on systems that only have wget.

**Comment by pietro** [comment]
The install script also blindingly runs `sudo`. The main `summon` install script doesn't have these issues.

**Comment by sgnn7** [comment]
Hey @pietro,
This issue is now closed via #39. Apologies for the delay on implementing this fix (it was in the backlog for a while now) and thank you for reporting it!
