### ISSUE TITLE
New release v0.4.0

### ISSUE THREAD

**Issue by pinmarva** [cyberark/summon-aws-secrets#41]
When do you think that you will release the version 4.0.0 with the last commits?

**Comment by izgeri** [comment]
@pinmarva I've created a pre-release here: https://github.com/cyberark/summon-aws-secrets/releases/tag/v0.4.0

I would like to run some smoke tests before promoting to a full release - but feel free to check it out if you'd like. It include the changes you contributed. Thanks you!!

**Comment by izgeri** [comment]
@pinmarva we've run smoke tests for our common use cases, but we haven't run through anything using `AWS_ROLE_ARN` yet (the use case you made the changes for). Please let us know if you run into any issues using it that way! Thanks again for your help with this project.
